apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgit
  labels:
    app: testgit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgit
  minReadySeconds: 5  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: testgo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: testgit
        image: gcr.io/winbet-thai/testgit-dev:latest
        imagePullPolicy: Always
        env:
        - name: NodeName
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GIN_MODE
          value: debug
        - name: TZ
          value: Asia/Taipei
        - name: database
          value: 10.148.0.72
        - name: redis
          value: "10.148.0.63:6379"
        - name: version
          value: "%v"
        - name: run
          value: "1"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
        ports:
        - containerPort: 8888
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: svr-role
                operator: NotIn
                values:
                - nfs
---
apiVersion: v1
kind: Service
metadata:
  name: testgit
spec:
  type: NodePort
  selector:
      app: testgit
  ports:
    - name: http
      port: 8888
      targetPort: 8888
