on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{env.GH_TOKEN}}" \
          "https://api.github.com/orgs/igs-treasure-island/repos" 2>/dev/null | \
          grep \"full_name\":| cut -d/ -f 2|cut -d\" -f 1
  use_api2:
    name: Loop test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        my_var: [ "a", "b", "c" ]
    steps:
      - name: test loop
        run: |
          echo "This is $my_var"
