on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{env.GH_TOKEN}}" \
          "https://api.github.com/orgs/igs-treasure-island/repos" 2>/dev/null | \
          grep \"full_name\":| cut -d/ -f 2|cut -d\" -f 1 > /tmp/list.txt
          LIST=`cat /tmp/list.txt`
          echo $LIST
          JQ=`cat /tmp/list.txt | jq -Rsc '. / "\n" - [""]'`
          echo "matrix=$JQ" >> $GITHUB_OUTPUT
  use_api2:
    needs: use_api
    name: Loop test
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        var: ${{ fromJSON(needs.use_api.outputs.matrix) }}
    steps:
      - name: test loop
        run: |
          echo "This is ${{matrix.var}}"
