on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GIT_TOKEN}}" "https://api.github.com/orgs/igs-treasure-island/repos" | \
          grep \"full_name\":| cut -d/ -f 2|cut -d\" -f 1|sort

