name: API test for check build
on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: 
      group: ubuntu-runners
    steps:
      - id: set-matrix
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{env.GH_TOKEN}}" \
          "https://api.github.com/orgs/igs-treasure-island/repos" 2>/dev/null > output.txt
          cat output.txt
          

