# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build TestGo and Publish

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Build
      run: go build -v ./...
    - name: Push to GCR GitHub Action
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.WINBET_THAI }}
        registry: gcr.io
        project_id: winbet-thai
        image_name: testgit-dev
        image_tag: latest,v1
        dockerfile: ./Dockerfile
        context: .
    - name: Remark version
      run: |
        BUILD_NUMBER=${{github.run_number}}
        sed -i "s/%v/$BUILD_NUMBER/g" kube/thai-test.yaml
    - name: docker-build-push-gcr-update-gke-deployment-action
      uses: budtendr/docker-build-push-gcr-update-gke-deployment-action@1.4
      with:
        # Base64 encoded service account JSON from GCP IAM service account
        service_account: ${{ secrets.WINBET_THAI }}
        # Cluster Zone
        zone: asia-southeast1-a
        # Project ID from GCP
        project_id: winbet-thai
        # GCR registry host, It could be gcr.io/us.gcr.io/eu.gcr.io/asia.gcr.io
        registry: gcr.io # default is gcr.io
        # Name of the image
        image_name: testgit-dev
        # Name of GKE cluster
        cluster: thai-test-slot-cluster-1
        # Namespace of the deployment
        namespace: default # default is default
        # Name of the deployment which needs to be update
        deployment: kube/thai-test.yaml
        # Name of container whose image needs to be updated
        container: testgit-dev
              
