name: Lint Go Code

on:
  workflow_dispatch:

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: 
      group: ubuntu-runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # 替換成你實際使用的 Go 版本

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest  # 或指定版本，如 v1.57.2
          args: --timeout 5m
