name: Nuke the world

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: 
      group: ubuntu-runners
    name: A job to say hello
    steps:
      - name: bar
        shell: bash
        run: |
          cat ${{secrets.UNIT_TEST_DATABASE_B64}} | base64 -d
          
      
