name: Nuke the world

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: igs-treasure-island/action-deploy-gke@main
        with:
          CREDENTIALS: ${{ secrets.WINBET_THAI }}
          PROJECT_ID: winbet-thai
          CLUSTER: thai-test-slot-cluster-1
          ZONE: asia-southeast1-a
          MANIFESTS: kube/thai-test.yaml
