name: '尋找並執行全專案的unit test action'
on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: 
      group: ubuntu-runners
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      tag: ${{ steps.set-matrix.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - id: set-matrix
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          #curl -L \
          #-H "Accept: application/vnd.github+json" \
          #-H "Authorization: token ${{env.GH_TOKEN}}" \
          #"https://api.github.com/orgs/igs-treasure-island/repos" 2>/dev/null | \
          #grep \"full_name\":| cut -d/ -f 2|cut -d\" -f 1|grep -v -f .unittestignore > /tmp/list.txt
          #LIST=`cat /tmp/list.txt`
          LIST=`cat .unittest`
          echo $LIST
          JQ=`cat /tmp/list.txt | jq -Rsc '. / "\n" - [""]'`
          echo "matrix=$JQ" >> $GITHUB_OUTPUT
          TAG=`date +%Y%m%d`_production
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  use_api2:
    needs: use_api
    name: Loop test
    runs-on: 
      group: ubuntu-runners
    strategy:
      matrix: 
        var: ${{ fromJSON(needs.use_api.outputs.matrix) }}
    steps:
      - name: test loop
        env: 
          TAG: ${{ needs.use_api.outputs.tag }}
        run: |
          echo "This is ${{matrix.var}} TAG=$TAG"
