name: Telegram Message Token

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      group: ubuntu-runners
    name: Jenkins
    steps:
      - name: Jenkins
        shell: bash
        run: |
          echo ${{secrets.TG_ROBOT_TOKEN_B64}}
